name: Process Fillout Data

on:
  repository_dispatch:
    types: [fillout_data]

jobs:
  process-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create directory and save data
        run: |
          mkdir -p sclients/
          echo "${{ toJson(github.event.client_payload.data) }}" > sclients/client_$(date +'%Y%m%d_%H%M%S').json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add sclients/
          git commit -m "Add new client data from Fillout"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
