name: Process Submissions from Fillout

on:
  repository_dispatch:
    types: [fillout_data]

jobs:
  process-submissions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Submissions from Fillout API
        run: |
          echo "Fetching submissions from Fillout API..."
          curl -H "Authorization: Bearer ${{ secrets.FILL_OUT_API_KEY }}" \
          "https://api.fillout.com/v1/api/forms/2akCiouB4Bus/submissions" \
          -o submissions.json

      - name: Validate JSON
        run: |
          if [ -s submissions.json ]; then
            echo "JSON файлът е валиден и непразен."
          else
            echo "Error: submissions.json е празен или липсва."
            exit 1
          fi

      - name: Process and Save Submissions with Client Name and Date
        run: |
          echo "Processing submissions..."
          mkdir -p fillout_data
          jq -c '.responses[]' submissions.json | while read submission; do
            # Извличане на ID и дата
            id=$(echo "$submission" | jq -r '.submissionId // "UnknownID"')
            date=$(echo "$submission" | jq -r '.submissionTime // "1970-01-01T00:00:00"' | sed 's/[^0-9]//g')

            # Извличане на името на клиента от questions[]
            name=$(echo "$submission" | jq -r '.questions[] | select(.name=="Вашето име?") | .value // "UnknownClient"')

            # Замяна на интервали в името с долни черти
            name_safe=$(echo "$name" | sed 's/ /_/g')

            # Създаване на файл с име на клиента и дата
            filename="${name_safe}_${date}.json"
            echo "$submission" > fillout_data/$filename
          done
          echo "Processed submissions saved in fillout_data:"
          ls -l fillout_data/

      - name: Commit and Push Processed Data
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add fillout_data/
          git commit -m "Add processed submissions with client names"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
