name: Webhook Trigger to Process Data

on:
  repository_dispatch:
    types: [fillout_data]

jobs:
  process-submissions:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Create a Trigger File in sclients
      - name: Create Trigger File
        run: |
          echo "Creating trigger file in sclients..."
          mkdir -p sclients/
          echo "{\"triggered_at\": \"$(date +'%Y-%m-%dT%H:%M:%S')\"}" > sclients/trigger_$(date +'%Y%m%d_%H%M%S').json
          echo "Trigger file created:"
          ls -l sclients/

      # 3. Fetch submissions from Fillout API
      - name: Fetch submissions from Fillout
        run: |
          echo "Fetching submissions from Fillout API..."
          curl -H "Authorization: Bearer ${{ secrets.FILL_OUT_API_KEY }}" \
          "https://api.fillout.com/v1/api/forms/2akCiouB4Bus/submissions" \
          -o submissions.json
          echo "Fetched submissions.json:"
          ls -l
          cat submissions.json || echo "submissions.json is empty or missing."

      # 4. Validate submissions.json
      - name: Validate submissions.json
        run: |
          echo "Validating submissions.json..."
          if [ -s submissions.json ]; then
            echo "submissions.json is not empty."
          else
            echo "Error: submissions.json is empty or invalid."
            exit 1
          fi

      # 5. Process and Save Submissions
      - name: Process and Save Submissions
        run: |
          echo "Processing submissions..."
          mkdir -p fillout_data
          jq -c 'if type=="array" then .[] elif .data then .data[] else empty end' submissions.json | while read submission; do
            id=$(echo "$submission" | jq -r '.id // "UnknownID"')
            date=$(echo "$submission" | jq -r '.createdAt // "19700101T000000"' | sed 's/[^0-9]//g')
            echo "$submission" > fillout_data/${id}_${date}.json
          done
          echo "Processed submissions saved in fillout_data:"
          ls -l fillout_data/

      # 6. Commit and Push Data
      - name: Commit and Push Trigger and Processed Data
        run: |
          echo "Committing and pushing trigger and processed data..."
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add sclients/ fillout_data/
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit. Skipping commit step."
          else
            git commit -m "Add trigger file and processed submissions"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
