name: Process Fillout Submissions

on:
  repository_dispatch:
    types: [fillout_data]

jobs:
  process-submissions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch submissions from Fillout
        run: |
          curl -H "Authorization: Bearer ${{ secrets.FILL_OUT_API_KEY }}" \
          "https://api.fillout.com/v1/api/forms/2akCiouB4Bus/submissions" \
          -o submissions.json

      - name: Log fetched submissions.json
        run: |
          echo "Fetched submissions:"
          cat submissions.json

      - name: Validate submissions.json
        run: |
          if [ -s submissions.json ]; then
            echo "submissions.json is not empty."
          else
            echo "Error: submissions.json is empty."
            exit 1
          fi

      - name: Process and Save Each Submission
        run: |
          mkdir -p fillout_data
          jq -c '.[]' submissions.json | while read submission; do
            id=$(echo "$submission" | jq -r '.id // "UnknownID"')
            date=$(echo "$submission" | jq -r '.createdAt // "19700101T000000"' | sed 's/[^0-9]//g')
            echo "$submission" > fillout_data/${id}_${date}.json
          done
          echo "Saved submissions:"
          ls -l fillout_data

      - name: Commit and Push Processed Data
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add fillout_data/
          git commit -m "Add processed submissions from Fillout"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
